/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myapp;

import org.junit.jupiter.api.Test;

import myapp.model.ProductRepository;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
